### PR TITLE
could you do the thing

### PR DESCRIPTION
**Pull request by UserSniper**
add me to repissitory

### CODE REVIEW

**Comment by LNLenost** [comment]
Hey, are you the guy who's going to work on this?

If you are, GL first of all!
Second, if you don't wanna start from scratch I made some basic things [here.](https://lnlenost.github.io/FamidashWeb) You can work from this and then expand it if you want.

Have a nice day!

**Comment by UserSniper** [comment]
> Hey, are you the guy who's going to work on this?
> 
> If you are, GL first of all! Second, if you don't wanna start from scratch I made some basic things [here.](https://lnlenost.github.io/FamidashWeb) You can work from this and then expand it if you want.
> 
> Have a nice day!

ello
dw, i saw your fork and thought it looked pretty superb
will definitely carry over some elements from it

**Comment by LNLenost** [comment]
> > Hey, are you the guy who's going to work on this?
> > 
> > If you are, GL first of all! Second, if you don't wanna start from scratch I made some basic things [here.](https://lnlenost.github.io/FamidashWeb) You can work from this and then expand it if you want.
> > 
> > Have a nice day!
> 
> ello
> dw, i saw your fork and thought it looked pretty superb
> will definitely carry over some elements from it

Ok! Good luck!

**Comment by UserSniper** [comment]
closing

**Pull request closed without merging**
